'use strict';
const $ = id => document.getElementById(id);
let busy = false;
async function health() {
  try {
    const response = await fetch('/api/health');
    if (!response.ok) throw new Error();
    const data = await response.json();
    $('health').textContent = data.ready
      ? `${data.source} · ${data.chunks} chunks · ${data.dimensions} dimensions · ready`
      : data.message;
    $('health').classList.toggle('ready', data.ready);
  } catch { $('health').textContent = 'Cannot reach the backend. Start it with: python -m rag_lab serve'; }
}
function showEvidence(matches) {
  $('evidence').replaceChildren();
  $('evidence-section').hidden = false;
  $('evidence-count').textContent = `${matches.length} passage${matches.length === 1 ? '' : 's'}`;
  for (const hit of matches) {
    const article = document.createElement('article');
    const heading = document.createElement('header');
    const id = document.createElement('strong'); id.textContent = hit.id;
    const score = document.createElement('span'); score.textContent = `Similarity ${hit.score.toFixed(3)}`;
    heading.append(id, score);
    const passage = document.createElement('p'); passage.textContent = hit.text; passage.dir = 'auto';
    const meta = document.createElement('p'); meta.className = 'meta';
    meta.textContent = `${hit.source} · characters [${hit.start}, ${hit.end})`;
    article.append(heading, passage, meta); $('evidence').append(article);
  }
}
async function run(generate) {
  if (busy) return;
  const question = $('question').value.trim();
  if (!question) { $('question').focus(); $('status').textContent = 'Enter a question first.'; return; }
  busy = true; $('ask').disabled = $('retrieve').disabled = true;
  $('status').className = '';
  $('status').textContent = generate ? 'Retrieving evidence and generating an answer…' : 'Searching the local index…';
  for (const id of ['answer-section', 'evidence-section', 'trace-section']) $(id).hidden = true;
  try {
    const response = await fetch(generate ? '/api/ask' : '/api/retrieve', {
      method: 'POST', headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({question, top_k: Number($('top-k').value)})
    });
    const data = await response.json();
    if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : 'Check your question and try again.');
    showEvidence(data.matches);
    if (generate) {
      // Never render model output or document text as HTML.
      $('answer').textContent = data.answer;
      $('warnings').textContent = data.citation_warnings.join(' ');
      $('model').textContent = `Generated by ${data.generation_model}. Verify the answer against the evidence below.`;
      $('answer-section').hidden = false;
    }
    $('trace').replaceChildren();
    for (const step of data.trace || ['Embed the question', 'Rank document chunks', 'Display the top matches']) {
      const li = document.createElement('li'); li.textContent = step; $('trace').append(li);
    }
    $('trace-section').hidden = false;
    $('status').textContent = generate ? 'Answer ready. Compare its citations with the evidence.' : 'Retrieval complete. No answer was generated.';
  } catch (error) {
    $('status').className = 'error';
    $('status').textContent = error.message === 'Failed to fetch' ? 'Cannot reach the backend. Check that the server is running.' : error.message;
  } finally { busy = false; $('ask').disabled = $('retrieve').disabled = false; }
}
$('question-form').addEventListener('submit', event => {event.preventDefault(); run(true);});
$('retrieve').addEventListener('click', () => run(false));
health();

document.querySelectorAll('[data-question]').forEach(button => {
  button.addEventListener('click', () => { $('question').value = button.dataset.question; $('question').focus(); });
});
